import React from 'react';
import { CODFormData } from '../../types/document';
import { COD_TEMPLATE_FIXED_TEXT } from '../../config/codTemplate';
import { formatDateDMY, formatOrdinalDate } from '../../utils/formatters';
import { PageFooter } from './PageFooter';

interface CODDocumentViewProps {
  formData: CODFormData;
}

export const CODDocumentView: React.FC<CODDocumentViewProps> = ({ formData }) => {
  const formattedLetterDate = formatDateDMY(formData.letterDate || new Date());
  const formattedJointDate = formatDateDMY(formData.jointReadingDate);
  const formattedBillingDate = formatOrdinalDate(formData.firstBillingReadingDate);

  return (
    <div className="flex flex-col items-center justify-start space-y-8 py-4 w-full select-text">
      {/* PAGE 1 */}
      <div className="a4-page shadow-2xl rounded-sm border border-slate-200">
        <div>
          {/* Header Bar & Logo */}
          <div className="flex items-start justify-between mb-6">
            <div className="w-56 h-2.5 bg-[#07833F] rounded-r-full"></div>
            <img
              src="/minusco2_logo.jpg"
              alt="Minus CO2"
              className="h-10 object-contain"
            />
          </div>

          {/* Top Date */}
          <div className="text-right text-[10.5pt] text-gray-800 font-medium mb-6">
            Date:{formattedLetterDate}
          </div>

          {/* Recipient Address */}
          <div className="mb-6 text-[10.5pt] text-gray-900 leading-snug">
            <p className="font-semibold text-gray-900 mb-0.5">To</p>
            <p className="font-bold text-gray-900">{formData.clientName || '[Client Name]'}</p>
            {formData.clientAddress ? (
              formData.clientAddress.split('\n').map((line, i) => (
                <p key={i} className="text-gray-800">
                  {line}
                </p>
              ))
            ) : (
              <p className="text-gray-400 italic">[Client Address]</p>
            )}
          </div>

          {/* Subject & Salutation */}
          <div className="mb-5 space-y-3">
            <p className="font-bold text-gray-900 text-[11pt]">
              {COD_TEMPLATE_FIXED_TEXT.subject}
            </p>
            <p className="font-medium text-gray-900 text-[10.5pt]">
              {COD_TEMPLATE_FIXED_TEXT.salutation}
            </p>
          </div>

          {/* Main Paragraph 1 */}
          <div className="mb-4 text-[10.5pt] text-gray-900 leading-relaxed text-justify">
            I am pleased to inform you that the installation of{' '}
            <span className="font-bold">{formData.systemCapacity || '71.98'} KWp</span> Solar System
            For <span className="font-bold">{formData.building || 'D-Wing'}</span> (
            <span className="font-bold">{formData.phase || 'Phase 2'}</span>) has been Completed
            along with the Generation Meter and Net Meter has been successfully completed. Today, we
            jointly took the first reading with Ms{' '}
            <span className="font-semibold underline decoration-slate-400 underline-offset-2">
              {formData.jointReadingPersonName || '[Person Name]'}
            </span>{' '}
            the official from your society. This marks an important milestone in our journey towards
            sustainable energy.
          </div>

          {/* Main Paragraph 2 */}
          <div className="mb-6 text-[10.5pt] text-gray-900 leading-relaxed text-justify">
            The solar generation meter calculates the amount of energy generated by the solar power
            plant. The net meter measures both import and export units to determine the amount of energy
            consumed from <span className="font-semibold">{formData.energyProvider || '[Energy Provider]'}</span>.
            Finally, the check meter is used to verify the reading of the generation meter.
          </div>

          {/* Readings Intro */}
          <div className="mb-4 text-[10.5pt] text-gray-900 font-medium">
            Please find the joint readings taken on Date:{' '}
            <span className="font-bold underline decoration-slate-400 underline-offset-2">
              {formattedJointDate}
            </span>
          </div>

          {/* Dynamic Meter Readings List */}
          <div className="mb-8 pl-4 space-y-3 text-[10.5pt] text-gray-900">
            {formData.generationMeters && formData.generationMeters.length > 0 ? (
              formData.generationMeters.map((meter, index) => {
                const isSingle = formData.generationMeters.length === 1;

                if (isSingle) {
                  return (
                    <div key={meter.id} className="space-y-1.5 font-medium">
                      <p>
                        1. Generation Meter:{' '}
                        <span className="font-bold underline decoration-slate-400 underline-offset-2">
                          {meter.generationReading || '0.0 KWH'}
                        </span>
                      </p>
                      <p>
                        2. Net Meter: A) Import:{' '}
                        <span className="font-semibold underline decoration-slate-400 underline-offset-2 min-w-[80px] inline-block">
                          {meter.netImport ? `${meter.netImport} KWH` : '________'}
                        </span>{' '}
                        B) Export:{' '}
                        <span className="font-semibold underline decoration-slate-400 underline-offset-2 min-w-[80px] inline-block">
                          {meter.netExport ? `${meter.netExport} KWH` : '________'}
                        </span>
                      </p>
                    </div>
                  );
                }

                return (
                  <div key={meter.id} className="space-y-1 p-3 rounded-lg bg-gray-50 border border-gray-100">
                    <p className="font-bold text-gray-900">
                      {index + 1}. Generation Meter:{' '}
                      <span className="underline decoration-slate-400 underline-offset-2">
                        {meter.generationReading || '0.0 KWH'}
                      </span>
                    </p>
                    <p className="pl-4 font-medium">
                      Net Meter: A) Import:{' '}
                      <span className="font-semibold underline decoration-slate-400 underline-offset-2 mr-4">
                        {meter.netImport ? `${meter.netImport} KWH` : '________'}
                      </span>
                      B) Export:{' '}
                      <span className="font-semibold underline decoration-slate-400 underline-offset-2">
                        {meter.netExport ? `${meter.netExport} KWH` : '________'}
                      </span>
                    </p>
                  </div>
                );
              })
            ) : (
              <p className="text-gray-400 italic text-sm">No meter readings recorded.</p>
            )}
          </div>

          {/* Joint Reading Signature Block */}
          <div className="mt-8 pt-4 border-t border-gray-100 text-[10.5pt] text-gray-900 space-y-2">
            <p className="font-bold">{COD_TEMPLATE_FIXED_TEXT.jointSignHeading}</p>
            <p className="font-medium">
              Name:{' '}
              <span className="font-semibold">{formData.jointReadingPersonName || '[Official Name]'}</span>
            </p>
            <div className="flex items-baseline space-x-2">
              <span className="font-medium">Sign:</span>
              <div className="w-48 border-b border-gray-400 h-6"></div>
            </div>
          </div>
        </div>

        {/* Page 1 Footer */}
        <PageFooter />
      </div>

      {/* PAGE 2 */}
      <div className="a4-page shadow-2xl rounded-sm border border-slate-200">
        <div>
          {/* Header Bar & Logo */}
          <div className="flex items-start justify-between mb-8">
            <div className="w-56 h-2.5 bg-[#07833F] rounded-r-full"></div>
            <img
              src="/minusco2_logo.jpg"
              alt="Minus CO2"
              className="h-10 object-contain"
            />
          </div>

          {/* Page 2 Paragraph 1 */}
          <div className="mb-6 text-[10.5pt] text-gray-900 leading-relaxed text-justify">
            {COD_TEMPLATE_FIXED_TEXT.page2Paragraph1}
          </div>

          {/* Page 2 Paragraph 2 */}
          <div className="mb-6 text-[10.5pt] text-gray-900 leading-relaxed text-justify">
            <span className="font-bold">Please note:</span> Our first readings for billing is scheduled
            for <span className="font-bold">{formattedBillingDate || '[Date]'}</span>. The generation
            invoice will be sent to you between the 1st and 5th of the following month, and the payment
            due date would be 15 days from the invoice date.
          </div>

          {/* Closing */}
          <div className="mb-12 text-[10.5pt] text-gray-900 font-medium">
            {COD_TEMPLATE_FIXED_TEXT.closing}
          </div>

          {/* Signatory Block */}
          <div className="text-[10.5pt] text-gray-900 space-y-1">
            <p className="font-extrabold tracking-wide uppercase text-gray-900">
              For {formData.issuingCompany ? formData.issuingCompany.toUpperCase() : 'MINUS CO2 SOLAR ASSIST LLP.'}
            </p>
            
            {/* Blank area for physical signature */}
            <div className="h-20 w-56 flex items-end pb-2">
              <span className="text-xs text-gray-300 italic font-mono">[ Sign Here ]</span>
            </div>

            <p className="font-bold tracking-tight text-gray-900">
              {formData.signatoryName || 'AKSHAY PATIL.'}
            </p>
            <p className="font-medium text-gray-800">
              {formData.signatoryDesignation || 'Manager- Accounts & Administration.'}
            </p>
          </div>
        </div>

        {/* Page 2 Footer */}
        <PageFooter />
      </div>
    </div>
  );
};
