export const COD_TEMPLATE_FIXED_TEXT = {
  subject: 'Subject: Commercial Operational Date (COD) Intimation',
  salutation: 'Dear Chairman / Secretary / Treasurer.',
  
  paragraph1: (capacity: string, building: string, phase: string, personName: string) =>
    `I am pleased to inform you that the installation of ${capacity} KWp Solar System For ${building} (${phase}) has been Completed along with the Generation Meter and Net Meter has been successfully completed. Today, we jointly took the first reading with Ms ${personName} the official from your society. This marks an important milestone in our journey towards sustainable energy.`,

  paragraph2: (provider: string) =>
    `The solar generation meter calculates the amount of energy generated by the solar power plant. The net meter measures both import and export units to determine the amount of energy consumed from ${provider}. Finally, the check meter is used to verify the reading of the generation meter.`,

  readingsIntro: (dateStr: string) =>
    `Please find the joint readings taken on Date: ${dateStr}`,

  jointSignHeading: 'Joint Reading person Name with Sign',
  
  page2Paragraph1:
    'As you may know, the net meter is a crucial component of the solar energy system that enables you to enjoy the benefits of clean energy. Your society will now start generating profits through the use of renewable energy, which will lead to cost savings and contribute to a cleaner environment.',

  page2Paragraph2: (formattedBillingDate: string) =>
    `Please note: Our first readings for billing is scheduled for ${formattedBillingDate}. The generation invoice will be sent to you between the 1st and 5th of the following month, and the payment due date would be 15 days from the invoice date.`,

  closing: 'Thank you for choosing us as your partner in sustainable energy.',

  forCompany: (companyName: string) => {
    // Format "For MINUS CO2 SOLAR ASSIST LLP." or "For MINUS CO2 PVT. LTD."
    const cleanCompany = companyName.trim().toUpperCase();
    return `For ${cleanCompany}.`;
  }
};

export const INITIAL_FORM_DATA = {
  clientName: 'Manavsthal Tower CO-OP HSG.Society LTD',
  clientAddress: 'CTS No.2841, Village Malwani, Taluka-Borivali, off.Marve Road,\nMalad West, Mumbai - 400095',
  systemCapacity: '71.98',
  building: 'D-Wing',
  phase: 'Phase 2',
  jointReadingPersonName: 'Kinnari Koppikar',
  energyProvider: 'Adani',
  jointReadingDate: new Date().toISOString().split('T')[0],
  generationMeters: [
    {
      id: 'meter-1',
      generationReading: '0.0 KWH',
      netImport: '',
      netExport: '',
    },
  ],
  firstBillingReadingDate: '2026-02-28',
  letterDate: '', // Will be dynamically computed
  issuingCompany: 'Minus CO2 Solar Assist LLP.' as const,
  signatoryName: 'AKSHAY PATIL.',
  signatoryDesignation: 'Manager- Accounts & Administration.',
};
